#![deny(unsafe_code)]
#![allow(missing_docs)]
#![warn(clippy::unwrap_used)]
#![deny(clippy::panic)]
#![allow(clippy::arithmetic_side_effects)]
#![allow(clippy::expect_used)]
#![allow(clippy::indexing_slicing)] // Key prefix checks use bounded [..32] slices on verified-length keys

//! ML-DSA Keygen Regression + Sign/Verify Roundtrip Tests
//!
//! These tests use `try_keygen_with_rng` from the `fips204` crate with a
//! deterministic CSPRNG to generate keypairs, then verify:
//! 1. Keygen output matches recorded fingerprints (regression detection)
//! 2. Sign/verify roundtrip works correctly for each parameter set
//!
//! ## Why not full NIST ACVP vectors?
//!
//! ML-DSA signing (FIPS 204 Algorithm 7) uses internal randomness (rnd).
//! The `fips204` crate does not expose a `sign_with_rng` that lets us
//! inject test randomness, so signatures are non-deterministic. We verify
//! keygen determinism (via `try_keygen_with_rng`) and sign/verify
//! correctness (roundtrip), but cannot compare against a fixed expected
//! signature.
//!
//! ## Security Levels
//! - ML-DSA-44: NIST Security Level 2 (128-bit classical security)
//! - ML-DSA-65: NIST Security Level 3 (192-bit classical security)
//! - ML-DSA-87: NIST Security Level 5 (256-bit classical security)

use super::{NistKatError, decode_hex};
use fips204::ml_dsa_44;
use fips204::ml_dsa_65;
use fips204::ml_dsa_87;
use fips204::traits::{KeyGen, SerDes, Signer, Verifier};

/// Keygen fingerprint for ML-DSA.
pub struct MlDsaKeygenFingerprint {
    pub test_name: &'static str,
    /// First 32 bytes of the public key (hex), generated from a zero-seed RNG.
    pub pk_first32: &'static str,
    /// Expected public key length.
    pub pk_len: usize,
}

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{:02x}", x)).collect()
}

/// Deterministic RNG that cycles the seed bytes.
/// Used ONLY for keygen regression tests — not for production crypto.
///
/// `fips204 0.4.x` uses `rand_core 0.6` traits (its `try_keygen_with_rng`
/// signature: `<R: CryptoRng + RngCore>` where both are from `rand_core 0.6`).
/// We implement those traits via the `rand_core_0_6` workspace alias rather
/// than `rand_core 0.9` so the type satisfies `fips204`'s bound.
struct SeedRng([u8; 32]);

impl rand_core_0_6::RngCore for SeedRng {
    fn next_u32(&mut self) -> u32 {
        0
    }
    fn next_u64(&mut self) -> u64 {
        0
    }
    fn fill_bytes(&mut self, dest: &mut [u8]) {
        for (d, s) in dest.iter_mut().zip(self.0.iter().cycle()) {
            *d = *s;
        }
    }
    fn try_fill_bytes(&mut self, dest: &mut [u8]) -> Result<(), rand_core_0_6::Error> {
        self.fill_bytes(dest);
        Ok(())
    }
}

impl rand_core_0_6::CryptoRng for SeedRng {}

// Generated by fips204 v0.6.1 with try_keygen_with_rng(SeedRng([0;32])).
// Regenerate if the fips204 dependency is updated.

/// ML-DSA-44 keygen fingerprint
pub const ML_DSA_44_FINGERPRINT: MlDsaKeygenFingerprint = MlDsaKeygenFingerprint {
    test_name: "ML-DSA-44-Keygen-Seed-Zeros",
    pk_first32: "ba71f9f64e11baeb58fa9c6fbb6e14e61f18643dab495b47539a9166ca019813",
    pk_len: 1312,
};

/// ML-DSA-65 keygen fingerprint
pub const ML_DSA_65_FINGERPRINT: MlDsaKeygenFingerprint = MlDsaKeygenFingerprint {
    test_name: "ML-DSA-65-Keygen-Seed-Zeros",
    pk_first32: "424b2f267e58d5b3b44d71acfc6a656bb26950d57c61db1c880bcfa1feab443f",
    pk_len: 1952,
};

/// ML-DSA-87 keygen fingerprint
pub const ML_DSA_87_FINGERPRINT: MlDsaKeygenFingerprint = MlDsaKeygenFingerprint {
    test_name: "ML-DSA-87-Keygen-Seed-Zeros",
    pk_first32: "e45ffc8cc73db885dc662e62a18cd8e3803297117fa5658814a985b5ff1db7b4",
    pk_len: 2592,
};

/// Run ML-DSA-44 keygen regression + sign/verify roundtrip.
///
/// # Errors
/// Returns `NistKatError` if keygen fingerprint mismatches or sign/verify fails.
pub fn run_ml_dsa_44_kat() -> Result<(), NistKatError> {
    let fp = &ML_DSA_44_FINGERPRINT;
    let expected_pk_prefix = decode_hex(fp.pk_first32)?;

    let (pk, sk) = ml_dsa_44::try_keygen_with_rng(&mut SeedRng([0u8; 32]))
        .map_err(|e| NistKatError::ImplementationError(format!("keygen: {:?}", e)))?;

    let pk_bytes = pk.into_bytes();
    if pk_bytes.len() != fp.pk_len {
        return Err(NistKatError::TestFailed {
            algorithm: "ML-DSA-44".to_string(),
            test_name: fp.test_name.to_string(),
            message: format!("pk length: expected {}, got {}", fp.pk_len, pk_bytes.len()),
        });
    }
    if pk_bytes[..32] != expected_pk_prefix[..] {
        return Err(NistKatError::TestFailed {
            algorithm: "ML-DSA-44".to_string(),
            test_name: fp.test_name.to_string(),
            message: format!(
                "pk prefix mismatch: expected {}, got {}",
                fp.pk_first32,
                hex(&pk_bytes[..32])
            ),
        });
    }

    // Sign/verify roundtrip with empty message
    let sig = sk
        .try_sign(&[], &[])
        .map_err(|e| NistKatError::ImplementationError(format!("sign: {:?}", e)))?;
    let pk_restored = ml_dsa_44::PublicKey::try_from_bytes(pk_bytes)
        .map_err(|e| NistKatError::ImplementationError(format!("pk deser: {:?}", e)))?;
    if !pk_restored.verify(&[], &sig, &[]) {
        return Err(NistKatError::TestFailed {
            algorithm: "ML-DSA-44".to_string(),
            test_name: fp.test_name.to_string(),
            message: "Sign/verify roundtrip failed".to_string(),
        });
    }

    // Sign/verify with "abc" message
    let sig_abc = sk
        .try_sign(b"abc", &[])
        .map_err(|e| NistKatError::ImplementationError(format!("sign abc: {:?}", e)))?;
    if !pk_restored.verify(b"abc", &sig_abc, &[]) {
        return Err(NistKatError::TestFailed {
            algorithm: "ML-DSA-44".to_string(),
            test_name: fp.test_name.to_string(),
            message: "Sign/verify roundtrip for 'abc' failed".to_string(),
        });
    }

    Ok(())
}

/// Run ML-DSA-65 keygen regression + sign/verify roundtrip.
///
/// # Errors
/// Returns `NistKatError` if keygen fingerprint mismatches or sign/verify fails.
pub fn run_ml_dsa_65_kat() -> Result<(), NistKatError> {
    let fp = &ML_DSA_65_FINGERPRINT;
    let expected_pk_prefix = decode_hex(fp.pk_first32)?;

    let (pk, sk) = ml_dsa_65::try_keygen_with_rng(&mut SeedRng([0u8; 32]))
        .map_err(|e| NistKatError::ImplementationError(format!("keygen: {:?}", e)))?;

    let pk_bytes = pk.into_bytes();
    if pk_bytes.len() != fp.pk_len {
        return Err(NistKatError::TestFailed {
            algorithm: "ML-DSA-65".to_string(),
            test_name: fp.test_name.to_string(),
            message: format!("pk length: expected {}, got {}", fp.pk_len, pk_bytes.len()),
        });
    }
    if pk_bytes[..32] != expected_pk_prefix[..] {
        return Err(NistKatError::TestFailed {
            algorithm: "ML-DSA-65".to_string(),
            test_name: fp.test_name.to_string(),
            message: format!(
                "pk prefix mismatch: expected {}, got {}",
                fp.pk_first32,
                hex(&pk_bytes[..32])
            ),
        });
    }

    let sig = sk
        .try_sign(b"test", &[])
        .map_err(|e| NistKatError::ImplementationError(format!("sign: {:?}", e)))?;
    let pk_r = ml_dsa_65::PublicKey::try_from_bytes(pk_bytes)
        .map_err(|e| NistKatError::ImplementationError(format!("pk deser: {:?}", e)))?;
    if !pk_r.verify(b"test", &sig, &[]) {
        return Err(NistKatError::TestFailed {
            algorithm: "ML-DSA-65".to_string(),
            test_name: fp.test_name.to_string(),
            message: "Sign/verify roundtrip failed".to_string(),
        });
    }
    Ok(())
}

/// Run ML-DSA-87 keygen regression + sign/verify roundtrip.
///
/// # Errors
/// Returns `NistKatError` if keygen fingerprint mismatches or sign/verify fails.
pub fn run_ml_dsa_87_kat() -> Result<(), NistKatError> {
    let fp = &ML_DSA_87_FINGERPRINT;
    let expected_pk_prefix = decode_hex(fp.pk_first32)?;

    let (pk, sk) = ml_dsa_87::try_keygen_with_rng(&mut SeedRng([0u8; 32]))
        .map_err(|e| NistKatError::ImplementationError(format!("keygen: {:?}", e)))?;

    let pk_bytes = pk.into_bytes();
    if pk_bytes.len() != fp.pk_len {
        return Err(NistKatError::TestFailed {
            algorithm: "ML-DSA-87".to_string(),
            test_name: fp.test_name.to_string(),
            message: format!("pk length: expected {}, got {}", fp.pk_len, pk_bytes.len()),
        });
    }
    if pk_bytes[..32] != expected_pk_prefix[..] {
        return Err(NistKatError::TestFailed {
            algorithm: "ML-DSA-87".to_string(),
            test_name: fp.test_name.to_string(),
            message: format!(
                "pk prefix mismatch: expected {}, got {}",
                fp.pk_first32,
                hex(&pk_bytes[..32])
            ),
        });
    }

    let sig = sk
        .try_sign(b"test", &[])
        .map_err(|e| NistKatError::ImplementationError(format!("sign: {:?}", e)))?;
    let pk_r = ml_dsa_87::PublicKey::try_from_bytes(pk_bytes)
        .map_err(|e| NistKatError::ImplementationError(format!("pk deser: {:?}", e)))?;
    if !pk_r.verify(b"test", &sig, &[]) {
        return Err(NistKatError::TestFailed {
            algorithm: "ML-DSA-87".to_string(),
            test_name: fp.test_name.to_string(),
            message: "Sign/verify roundtrip failed".to_string(),
        });
    }
    Ok(())
}
