#![deny(unsafe_code)]
#![allow(missing_docs)]
#![warn(clippy::unwrap_used)]
#![deny(clippy::panic)]

//! ML-KEM Deterministic Keygen Regression Tests
//!
//! These tests use `keygen_from_seed(d, z)` from the `fips203` crate to generate
//! keypairs deterministically, then verify the output matches recorded fingerprints.
//! This catches implementation regressions (algorithm changes, dependency updates)
//! that silently alter keygen output.
//!
//! Additionally, each test verifies encaps/decaps roundtrip correctness — shared
//! secrets must match after a full encapsulate → decapsulate cycle.
//!
//! ## Why not full NIST ACVP vectors?
//!
//! NIST ACVP test vectors require matching the exact internal randomness injection
//! path (d, z for keygen; m for encaps). The `fips203` crate exposes
//! `keygen_from_seed` but encaps is still randomized internally, so we cannot
//! produce deterministic ciphertexts or shared secrets for comparison. The keygen
//! fingerprint + roundtrip approach provides strong regression coverage.
//!
//! ## Security Levels
//! - ML-KEM-512: NIST Security Level 1 (128-bit classical, quantum-safe)
//! - ML-KEM-768: NIST Security Level 3 (192-bit classical, quantum-safe)
//! - ML-KEM-1024: NIST Security Level 5 (256-bit classical, quantum-safe)

use super::{NistKatError, decode_hex};
use fips203::ml_kem_512;
use fips203::ml_kem_768;
use fips203::ml_kem_1024;
use fips203::traits::{Decaps, Encaps, KeyGen, SerDes};

/// Keygen fingerprint: first 32 bytes of ek and dk for a known seed.
pub struct MlKemKeygenFingerprint {
    pub test_name: &'static str,
    pub d: [u8; 32],
    pub z: [u8; 32],
    /// First 32 bytes of the encapsulation key (hex).
    pub ek_first32: &'static str,
    /// First 32 bytes of the decapsulation key (hex).
    pub dk_first32: &'static str,
    /// Expected encapsulation key length in bytes.
    pub ek_len: usize,
    /// Expected decapsulation key length in bytes.
    pub dk_len: usize,
}

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{:02x}", x)).collect()
}

// Generated by fips203 v0.4.3 with keygen_from_seed(d=[0;32], z=[0;32]).
// Regenerate if the fips203 dependency is updated.

/// ML-KEM-512 keygen fingerprints
pub const ML_KEM_512_FINGERPRINTS: &[MlKemKeygenFingerprint] = &[MlKemKeygenFingerprint {
    test_name: "ML-KEM-512-Keygen-Seed-Zeros",
    d: [0u8; 32],
    z: [0u8; 32],
    ek_first32: "df17848677416e954d66f9b09e1281532a2e8f0c6abe0037e7e8119097c9ec84",
    dk_first32: "87ca1993b64d8932ae3b225282a1b3c13765dcc1224c4377330a04ecec0b2505",
    ek_len: 800,
    dk_len: 1632,
}];

/// ML-KEM-768 keygen fingerprints
pub const ML_KEM_768_FINGERPRINTS: &[MlKemKeygenFingerprint] = &[MlKemKeygenFingerprint {
    test_name: "ML-KEM-768-Keygen-Seed-Zeros",
    d: [0u8; 32],
    z: [0u8; 32],
    ek_first32: "254a797885c63b1440aa389c65340ef33520cc039aa8d749ae7095ba8485a244",
    dk_first32: "79aa9d810589b8e80bc0799bf1eb8b866a6b5c8bbf99881be0025eb98902d282",
    ek_len: 1184,
    dk_len: 2400,
}];

/// ML-KEM-1024 keygen fingerprints
pub const ML_KEM_1024_FINGERPRINTS: &[MlKemKeygenFingerprint] = &[MlKemKeygenFingerprint {
    test_name: "ML-KEM-1024-Keygen-Seed-Zeros",
    d: [0u8; 32],
    z: [0u8; 32],
    ek_first32: "b1572c900b8b8202357437819c129e3cd66d21d7af55c5682b951deff475df1b",
    dk_first32: "8bb57f775b75158c5a12f8345d3a94d3859f4086a95c0c5372621436d084fc6a",
    ek_len: 1568,
    dk_len: 3168,
}];

/// Run ML-KEM-512 keygen regression + roundtrip test.
///
/// # Errors
/// Returns `NistKatError` if keygen fingerprint mismatches or roundtrip fails.
pub fn run_ml_kem_512_kat() -> Result<(), NistKatError> {
    for fp in ML_KEM_512_FINGERPRINTS {
        let expected_ek_prefix = decode_hex(fp.ek_first32)?;
        let expected_dk_prefix = decode_hex(fp.dk_first32)?;

        let (ek, dk) = <ml_kem_512::KG as KeyGen>::keygen_from_seed(fp.d, fp.z);
        let ek_bytes = ek.into_bytes();
        let dk_bytes = dk.into_bytes();

        // Verify key sizes
        if ek_bytes.len() != fp.ek_len {
            return Err(NistKatError::TestFailed {
                algorithm: "ML-KEM-512".to_string(),
                test_name: fp.test_name.to_string(),
                message: format!("ek length: expected {}, got {}", fp.ek_len, ek_bytes.len()),
            });
        }
        if dk_bytes.len() != fp.dk_len {
            return Err(NistKatError::TestFailed {
                algorithm: "ML-KEM-512".to_string(),
                test_name: fp.test_name.to_string(),
                message: format!("dk length: expected {}, got {}", fp.dk_len, dk_bytes.len()),
            });
        }

        // Verify keygen fingerprints
        if ek_bytes[..32] != expected_ek_prefix[..] {
            return Err(NistKatError::TestFailed {
                algorithm: "ML-KEM-512".to_string(),
                test_name: fp.test_name.to_string(),
                message: format!(
                    "ek prefix mismatch: expected {}, got {}",
                    fp.ek_first32,
                    hex(&ek_bytes[..32])
                ),
            });
        }
        if dk_bytes[..32] != expected_dk_prefix[..] {
            return Err(NistKatError::TestFailed {
                algorithm: "ML-KEM-512".to_string(),
                test_name: fp.test_name.to_string(),
                message: format!(
                    "dk prefix mismatch: expected {}, got {}",
                    fp.dk_first32,
                    hex(&dk_bytes[..32])
                ),
            });
        }

        // Roundtrip: encaps → decaps → shared secrets must match
        let ek_restored = ml_kem_512::EncapsKey::try_from_bytes(ek_bytes)
            .map_err(|e| NistKatError::ImplementationError(format!("ek deser: {:?}", e)))?;
        let dk_restored = ml_kem_512::DecapsKey::try_from_bytes(dk_bytes)
            .map_err(|e| NistKatError::ImplementationError(format!("dk deser: {:?}", e)))?;

        let (ss_sender, ct) = ek_restored
            .try_encaps()
            .map_err(|e| NistKatError::ImplementationError(format!("encaps: {:?}", e)))?;
        let ss_receiver = dk_restored
            .try_decaps(&ct)
            .map_err(|e| NistKatError::ImplementationError(format!("decaps: {:?}", e)))?;

        if ss_sender != ss_receiver {
            return Err(NistKatError::TestFailed {
                algorithm: "ML-KEM-512".to_string(),
                test_name: fp.test_name.to_string(),
                message: "Shared secrets do not match after encaps/decaps".to_string(),
            });
        }
    }
    Ok(())
}

/// Run ML-KEM-768 keygen regression + roundtrip test.
///
/// # Errors
/// Returns `NistKatError` if keygen fingerprint mismatches or roundtrip fails.
pub fn run_ml_kem_768_kat() -> Result<(), NistKatError> {
    for fp in ML_KEM_768_FINGERPRINTS {
        let expected_ek_prefix = decode_hex(fp.ek_first32)?;
        let expected_dk_prefix = decode_hex(fp.dk_first32)?;

        let (ek, dk) = <ml_kem_768::KG as KeyGen>::keygen_from_seed(fp.d, fp.z);
        let ek_bytes = ek.into_bytes();
        let dk_bytes = dk.into_bytes();

        if ek_bytes.len() != fp.ek_len || dk_bytes.len() != fp.dk_len {
            return Err(NistKatError::TestFailed {
                algorithm: "ML-KEM-768".to_string(),
                test_name: fp.test_name.to_string(),
                message: "Key length mismatch".to_string(),
            });
        }
        if ek_bytes[..32] != expected_ek_prefix[..] || dk_bytes[..32] != expected_dk_prefix[..] {
            return Err(NistKatError::TestFailed {
                algorithm: "ML-KEM-768".to_string(),
                test_name: fp.test_name.to_string(),
                message: format!(
                    "keygen fingerprint mismatch (ek: {}, dk: {})",
                    hex(&ek_bytes[..32]),
                    hex(&dk_bytes[..32])
                ),
            });
        }

        let ek_r = ml_kem_768::EncapsKey::try_from_bytes(ek_bytes)
            .map_err(|e| NistKatError::ImplementationError(format!("{:?}", e)))?;
        let dk_r = ml_kem_768::DecapsKey::try_from_bytes(dk_bytes)
            .map_err(|e| NistKatError::ImplementationError(format!("{:?}", e)))?;
        let (ss1, ct) =
            ek_r.try_encaps().map_err(|e| NistKatError::ImplementationError(format!("{:?}", e)))?;
        let ss2 = dk_r
            .try_decaps(&ct)
            .map_err(|e| NistKatError::ImplementationError(format!("{:?}", e)))?;
        if ss1 != ss2 {
            return Err(NistKatError::TestFailed {
                algorithm: "ML-KEM-768".to_string(),
                test_name: fp.test_name.to_string(),
                message: "Shared secrets mismatch".to_string(),
            });
        }
    }
    Ok(())
}

/// Run ML-KEM-1024 keygen regression + roundtrip test.
///
/// # Errors
/// Returns `NistKatError` if keygen fingerprint mismatches or roundtrip fails.
pub fn run_ml_kem_1024_kat() -> Result<(), NistKatError> {
    for fp in ML_KEM_1024_FINGERPRINTS {
        let expected_ek_prefix = decode_hex(fp.ek_first32)?;
        let expected_dk_prefix = decode_hex(fp.dk_first32)?;

        let (ek, dk) = <ml_kem_1024::KG as KeyGen>::keygen_from_seed(fp.d, fp.z);
        let ek_bytes = ek.into_bytes();
        let dk_bytes = dk.into_bytes();

        if ek_bytes.len() != fp.ek_len || dk_bytes.len() != fp.dk_len {
            return Err(NistKatError::TestFailed {
                algorithm: "ML-KEM-1024".to_string(),
                test_name: fp.test_name.to_string(),
                message: "Key length mismatch".to_string(),
            });
        }
        if ek_bytes[..32] != expected_ek_prefix[..] || dk_bytes[..32] != expected_dk_prefix[..] {
            return Err(NistKatError::TestFailed {
                algorithm: "ML-KEM-1024".to_string(),
                test_name: fp.test_name.to_string(),
                message: format!(
                    "keygen fingerprint mismatch (ek: {}, dk: {})",
                    hex(&ek_bytes[..32]),
                    hex(&dk_bytes[..32])
                ),
            });
        }

        let ek_r = ml_kem_1024::EncapsKey::try_from_bytes(ek_bytes)
            .map_err(|e| NistKatError::ImplementationError(format!("{:?}", e)))?;
        let dk_r = ml_kem_1024::DecapsKey::try_from_bytes(dk_bytes)
            .map_err(|e| NistKatError::ImplementationError(format!("{:?}", e)))?;
        let (ss1, ct) =
            ek_r.try_encaps().map_err(|e| NistKatError::ImplementationError(format!("{:?}", e)))?;
        let ss2 = dk_r
            .try_decaps(&ct)
            .map_err(|e| NistKatError::ImplementationError(format!("{:?}", e)))?;
        if ss1 != ss2 {
            return Err(NistKatError::TestFailed {
                algorithm: "ML-KEM-1024".to_string(),
                test_name: fp.test_name.to_string(),
                message: "Shared secrets mismatch".to_string(),
            });
        }
    }
    Ok(())
}
