#![deny(unsafe_code)]
#![no_main]

//! Fuzz testing for random number generation
//!
//! Tests that random generation functions handle various sizes
//! without crashing and produce unique outputs.

use latticearc::primitives::rand::csprng::{random_bytes, random_u32, random_u64};
use libfuzzer_sys::fuzz_target;

fuzz_target!(|data: &[u8]| {
    if data.is_empty() {
        return;
    }

    // Use first bytes to determine test parameters
    let size = ((data[0] as usize) % 256) + 1; // 1-256 bytes

    // Test 1: Generate random bytes of specified size
    let random_result: Vec<u8> = random_bytes(size);
    // Verify correct length
    assert_eq!(random_result.len(), size, "Generated bytes must have requested size");

    // Round-11 audit fix: probabilistic assertions on independent
    // CSPRNG output are inappropriate inside libfuzzer harnesses —
    // libfuzzer iterates millions of times, and even a 2^-128 collision
    // probability per call accumulates into a deterministic false-positive
    // crash over a sustained fuzz run. The harness now exercises the
    // call path without asserting on output content. The dudect /
    // Welch's-t side-channel suite and the SHA-256 monobit + chi-square
    // statistical tests cover RNG output quality on a separate cadence.
    let _ = random_result; // exercise the call path; do not assert on bytes

    // Test 2: Exercise the call path with two independent draws (no assertion).
    let _rand1: Vec<u8> = random_bytes(32);
    let _rand2: Vec<u8> = random_bytes(32);

    // Test 3: Generate various sizes
    for test_size in [1, 16, 32, 64, 128, 256] {
        let random: Vec<u8> = random_bytes(test_size);
        assert_eq!(random.len(), test_size);
    }

    // Test 4: Test random_u32 and random_u64
    let r1 = random_u32();
    let r2 = random_u32();
    // May be equal by chance, but very unlikely with good RNG
    let _ = (r1, r2);

    // Generate random u64
    let r3 = random_u64();
    let r4 = random_u64();
    let _ = (r3, r4);

    // Test 5: Zero size generation
    let empty: Vec<u8> = random_bytes(0);
    assert!(empty.is_empty(), "Zero size should produce empty result");

    // Test 6: Stress test - multiple rapid generations
    for _ in 0..10 {
        let _: Vec<u8> = random_bytes(32);
    }
});
